### ISSUE TITLE
Cannot load record "tl_simple_jobs_location.id=1".

### ISSUE THREAD

**Issue by akroii** [JanoschOltmanns/ContaoSimpleJobsBundle#1]
Hallo,
wenn man ein Archiv anlegt und darin einen Standort anlegen möchte erscheint ein Fehler:
`Cannot load record "tl_simple_jobs_location.id=1".`

Contao 4.9.9
Job Bundle: 1.0.0

**Comment by Tastaturberuf** [comment]
Kann ich nicht repoduzieren.
Contao 4.9.16
JobBundle 1.0.0

Wie ist dein Archiv konfiguriert? Hab bezüglich des Detail-Links einen anderen Bug gefixt. #7

**Comment by JanoschOltmanns** [comment]
@akroii besteht hier aktuell noch ein Problem? Kann ich es irgendwie reproduzieren?

**Comment by akroii** [comment]
Fehler tritt in v1.1.2 nicht mehr auf, Danke.
