### ISSUE TITLE
php 8 compatibility

### ISSUE THREAD

**Issue by rustykowski** [JanoschOltmanns/ContaoSimpleJobsBundle#12]
Die Erweiterung lässt sich aufgrund der PHP-requirements ^7.2 derzeit nicht unter PHP 8 installieren.
Ist die Beschränkung wirklich notwenig?

**Comment by JanoschOltmanns** [comment]
Aktuell noch nicht explizit getestet. Daher noch nicht hoch gesetzt. Prüfe ich mal und passe es an.

**Comment by rustykowski** [comment]
Hallo Janosch,
ich kann immerhin berichten, dass sich die Version 1.0.0 unter PHP 8.0 installieren lässt und funktioniert. Meinst du, dass die aktuelle Version deiner Erweiterung Probleme bereiten könnte? Ich würde dir gerne beim Testen helfen, weiß aber nicht wie. Es sei denn, du änderst die PHP-Constraints in der dev-master Version.

**Comment by JanoschOltmanns** [comment]
Ja, ändere ich doch gerne.

**Comment by rustykowski** [comment]
Wann könntest du die Änderung pushen?

**Comment by JanoschOltmanns** [comment]
@rustykowski bitte versuche mal https://github.com/JanoschOltmanns/ContaoSimpleJobsBundle/releases/tag/v1.2.0-alpha (Version 1.2.0 alpha). Da ist das Constraint für PHP um 8.0 erweitert.

**Comment by rustykowski** [comment]
Das klappt wunderbar mit PHP 8.0 – keine Warnungen oder Fehlermeldungen. Vielen Dank!

**Comment by rustykowski** [comment]
Halt stopp, die Detailansicht macht noch Probleme:
```Uncaught PHP Exception TypeError: "implode(): Argument #1 ($pieces) must be of type array, string given" at /var/www/.../httpdocs/.../vendor/janoscholtmanns/contao-simple-jobs-bundle/src/Resources/contao/templates/jobposting/jobposting_detail.html5 line 4 {"exception":"[object] (TypeError(code: 0)```

**Comment by rustykowski** [comment]
jobposting_detail.html5 Zeile 4: es fehlt nur das s am Ende von employmentType**s**.
Dort steht noch:
`<small><?= implode(', ', $this->employmentType) ?></small>`

**Comment by rustykowski** [comment]
Gleicher Fehler in Zeile 6 des Templates `jobposting_listitem.html5`.
Sorry, hatte vorher noch ein älteres angepasstes Template eingebunden.

**Comment by JanoschOltmanns** [comment]
Sollte mit 1.2.0 behoben sein (Detail und Liste): https://github.com/JanoschOltmanns/ContaoSimpleJobsBundle/releases/tag/v1.2.0

**Comment by rustykowski** [comment]
Super! Gerade noch rechtzeitig vor der [Contao Show: Clash of Jobs](https://www.youtube.com/watch?v=ColU1MSzCEI) ;-)

**Comment by JanoschOltmanns** [comment]
> Super! Gerade noch rechtzeitig vor der [Contao Show: Clash of Jobs](https://www.youtube.com/watch?v=ColU1MSzCEI) ;-)

Jawoll – war aber eher Zufall. Ich musste da eh für einen Relaunch dran.
