### ISSUE TITLE
employmentType wird nicht angezeigt

### ISSUE THREAD

**Issue by intradesign** [JanoschOltmanns/ContaoSimpleJobsBundle#16]
Hallo Janosch,
ich habe mal deine Jobs-Extension ausprobiert. Gefällt mir gut. Wie es aussieht, werden aber die empoloymentTypes nicht ausgegeben.

`$this->employmentType
`

Kann es sein, dass da was nicht stimmt?

Die Keywords funktionieren. Aber wenn ich Vollzeit und Teilzeit ausgeben möchte, müssten die immer einmal als Type und einmal als Keyword angelget werden.

Viele Grüße
Timo

**Comment by JanoschOltmanns** [comment]
Hallo Timo,

ich glaube, das gibt es bislang einen "Tippfehler". Schau mal unter `$this->employmentTypes`
