### ISSUE TITLE
Update läuft nicht...

### ISSUE THREAD

**Issue by intradesign** [JanoschOltmanns/ContaoSimpleJobsBundle#17]
Moin Janosch,
Version 1.1.2 lässt sich bei mir nicht installieren.

Composer-Meldung ist: ContaoSimpleJobs 1.1.2 benötigt PHP 7.2. Sonst keine weitere Meldung.

Ich bin bei PHP 8.1
Die Meldung Kommt mir irgendwie komisch vor.

Hast du eine Idee?

**Comment by JanoschOltmanns** [comment]
Ja. Aktuelles Release ist noch nicht für php 8.1 frei gegeben. Kommt am Montag.

**Comment by JanoschOltmanns** [comment]
Bitte mal mit dem aktuellen Release 1.2.0 (https://github.com/JanoschOltmanns/ContaoSimpleJobsBundle/releases/tag/v1.2.0) versuchen.
