### ISSUE TITLE
eye-icon in Backend-List does not correspond with published-state

### ISSUE THREAD

**Issue by rustykowski** [JanoschOltmanns/ContaoSimpleJobsBundle#9]
Contao 4.9.22, SimpleJobs 1.0.0
Der Veröffentlichungsstatus einer Stellenanzeige wird in der Backend-Liste nicht korrekt dargestellt. Aktivierung/Deaktivierung in der Liste über das grüne/graue Auge hat keine Auswirkungen auf den Veröffentlichungsstatus. Die Anzeige ist irreführend. 
Nur die Checkbox "Stellenanzeige veröffentlichen" in der Eingabemaske selbst wirkt sich konkret aus, korrespondiert aber nicht mit dem Auge in der Liste.

**Comment by JanoschOltmanns** [comment]
Sollte mit https://github.com/JanoschOltmanns/ContaoSimpleJobsBundle/pull/10 jetzt passen
